# index by 1 -- makes it easier for nav
set -g pane-base-index 1
set -g base-index 1

# Jump to pane by number
bind 1 select-pane -t 1
bind 2 select-pane -t 2
bind 3 select-pane -t 3
bind 4 select-pane -t 4

# Mouse Mode
set -g mouse on

# Pane Highlighting
set -g pane-active-border-style fg=green,bold
set -g pane-border-style fg=grey

bind r source-file ~/dotfiles/.tmux.conf \; display "Reloaded!"

# Enable clipboard integration on macOS
set -s copy-command 'pbcopy'
set -s set-clipboard on

# Default to use zsh
set-option -g default-shell /usr/bin/zsh


